# Generated by Django 2.2 on 2020-03-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodssku',
            name='desc',
            field=models.CharField(max_length=256, verbose_name='商品简介'),
        ),
    ]
