# Generated by Django 2.2 on 2020-04-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200330_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodssku',
            name='points',
            field=models.IntegerField(default=0, verbose_name='赠送积分'),
        ),
    ]
