# Generated by Django 2.2 on 2020-05-06 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ordergoods',
            table='fd_order_goods',
        ),
        migrations.AlterModelTable(
            name='orderinfo',
            table='fd_order_info',
        ),
    ]
